name: Deploy infrastructure to AWS

# This event allows me to manually trigger this job through the GitHub interface if needed.
# Additionally, it will run on push to the main branch or on a pull request to the main branch.
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["deploy/create/**"]
  pull_request:
    branches: [main]
    paths: ["deploy/create/**"]
  schedule:
    - cron: '0 13 1 * *' # Run the workflow on the first day of each month at 1:00 PM UTC

jobs:
  deploy-infra-to-AWS:
    runs-on: ubuntu-latest  # Specifies that the job will run on an Ubuntu machine.

    permissions:
      id-token: write      # Allows generating ID tokens for authentication with AWS.
      contents: read       # Allows reading the repository contents.

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out the code from the repository.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4  # Configures AWS credentials.
        with:
          role-to-assume: arn:aws:iam::677615602730:role/github-actions  # Specifies the IAM role to assume.
          aws-region: us-east-1  # Specifies the AWS region to use.
          mask-aws-account-id: 'true'  # Masks the AWS account ID in logs.

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # Sets up Terraform.

      - name: Terraform Init
        run: terraform init
        working-directory: deploy/create # Changes to the deploy directory to initialize Terraform.

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: deploy/create # Changes to the deploy directory to apply the Terraform configuration.
